name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run type checking
        run: bun run check
      - name: Run linting
        run: bun lint
      - name: Install browser
        run: bun playwright install
      - name: Run tests
        run: bun test
  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.11.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
